""""Temporary config file."""

import os

LOGGING_COLUMN1_WIDTH = 15
LOGGING_COLUMN2_WIDTH = 30
LOGGING_INDENT = "  "
LOOKUP_SENTINEL = ""
LOOKUP_SEPERATOR = "."
LOOKUP_STATIC_VALUE_MARKER = "~"
LOOKUP_TRANSFORMATION_PREFIX = "to_"
LOOP_COUNT = -1
NEW_LINE = os.linesep
