""""Environment variable definitions for text_lint."""

EXTENSIONS_LOCAL_ENV_VAR = "TEXT_LINT_EXTENSIONS_LOCAL_FOLDER"
EXTENSIONS_LOCAL_VAR_SEPERATOR = ":"
EXTENSIONS_THIRD_PARTY_ENV_VAR = "TEXT_LINT_EXTENSIONS_THIRD_PARTY"
EXTENSIONS_THIRD_PARTY_VAR_SEPERATOR = ":"
