---
version: "0.1.0"

settings:
  comment_regex: "^(#\\s|#[^!]).+$"

rules:
  - name: shebang is first line and properly index
    operation: assert_equal
    expected: "#!/usr/bin/make -f\n"

  - name: blank line after shebang
    operation: assert_blank

  - name: read all phonies
    operation: assert_regex
    regex: "^.PHONY: ([a-z-\\s]+)\\n"
    save: phonies
    splits:
      - group: 1
        separator: " "

  - name: blank line after phonies
    operation: assert_blank

  - name: read help entry
    operation: assert_equal
    expected: "help:\n"

  - name: read help title
    operation: assert_equal
    expected: "\t@echo \"Please use 'make <target>' where <target> is one of:\"\n"

  - name: read help content
    operation: assert_regex_section
    regex: "\\t@echo \"  ([a-z-]+)\\s+.+\n"
    save: helps

  - name: read aliases
    operation: assert_regex_section
    regex: "^([a-z]+): ([a-z-\\s]+)\n"
    save: aliases
    splits:
      - group: 2

  - name: read until eof
    operation: assert_sequence_begins
    count: -1
    rules:
      - name: read command entry
        operation: assert_regex
        regex: "^([a-z-]+):\n"
        save: commands

      - name: read command contents
        operation: assert_regex_section
        regex: "^\t@.+\n"

validators:
  - name: create expected phonies
    operation: validate_combine
    saved:
      - ~help
      - aliases.capture
      - commands.capture
    new_saved: expected_phonies

  - name: test alphabetical order
    operation: validate_equal
    saved_a:
      - aliases.capture.0
      - helps.capture.0
      - commands.capture.0
    saved_b:
      - aliases.capture.0.to_sorted
      - helps.capture.0.to_sorted
      - commands.capture.0.to_sorted

  - name: test for repeated entries
    operation: validate_equal
    saved_a:
      - aliases.capture.0
      - helps.capture.0
      - commands.capture.0
    saved_b:
      - aliases.capture.0.to_unique
      - helps.capture.0.to_unique
      - commands.capture.0.to_unique

  - name: test expected phonies and helps
    operation: validate_equal
    saved_a:
      - commands.capture
      - phonies.capture
    saved_b:
      - helps.capture
      - expected_phonies.capture
