---
version: "0.1.0"

settings:
  comment_regex: "^(#\\s|#[^!]).*$"

assertions:
  - name: shebang is first line and properly indexed
    operation: assert_equal
    expected: "#!/usr/bin/make -f"

  - name: blank line after shebang
    operation: assert_blank

  - name: read all phonies
    operation: assert_regex
    regex: "^.PHONY: ([a-z-\\s]+)$"
    save: phonies
    splits:
      - group: 1
        separator: " "

  - name: blank line after phonies
    operation: assert_blank

  - name: read help entry
    operation: assert_equal
    expected: "help:"

  - name: read help title
    operation: assert_equal
    expected: "\t@echo \"Please use 'make <target>' where <target> is one of:\""

  - name: read help content
    operation: assert_regex_section
    regex: "^\\t@echo \"  ([a-z-]+)\\s+.+$"
    save: helps

  - name: blank line after help
    operation: assert_blank

  - name: read aliases
    operation: assert_regex_section
    regex: "^([a-z]+): ([a-z-\\s]+)$"
    save: aliases
    splits:
      - group: 2

  - name: read until eof
    operation: assert_sequence_begins
    count: -1
    assertions:

      - name: blank line before command
        operation: assert_blank

      - name: read command entry
        operation: assert_regex
        regex: "^([a-z-]+):$"
        save: commands

      - name: read command contents
        operation: assert_regex_section
        regex: "^\\t@.+$"

validators:
  - name: create expected phonies
    operation: validate_combine
    saved:
      - ~help
      - aliases.capture(1)
      - commands.capture(1)
    new_saved: expected_phonies

  - name: test alphabetical order
    operation: validate_equal
    saved_a:
      - aliases.capture(1)
      - helps.capture(1)
      - commands.capture(1)
    saved_b:
      - aliases.capture(1).to_sorted()
      - helps.capture(1).to_sorted()
      - commands.capture(1).to_sorted()

  - name: test for repeated entries
    operation: validate_equal
    saved_a:
      - aliases.capture(1)
      - helps.capture(1)
      - commands.capture(1)
    saved_b:
      - aliases.capture(1).to_unique()
      - helps.capture(1).to_unique()
      - commands.capture(1).to_unique()

  - name: test expected phonies and helps
    operation: validate_equal
    saved_a:
      - commands.capture(1)
      - phonies.capture(1).0
    saved_b:
      - helps.capture(1)
      - expected_phonies.capture(1)
