---
version: "0.1.0"

settings:
  comment_regex: "^(#\\s|#[^!]).+$"

rules:
  - name: shebang is first line and properly index
    operation: assert_equal
    expected: "#!/usr/bin/make -f\n"

  - name: blank line after shebang
    operation: assert_blank

  - name: read all phonies
    operation: assert_regex
    regex: "^.PHONY: ([a-z-\\s]+)\\n"
    save: phonies
    splits:
      - group: 1
        separator: " "

  - name: blank line after phonies
    operation: assert_blank

  - name: read help entry
    operation: assert_equal
    expected: "help:\n"

  - name: read help title
    operation: assert_equal
    expected: "\t@echo \"Please use 'make <target>' where <target> is one of:\"\n"

  - name: read help content
    operation: assert_regex_section
    regex: "\\t@echo \"  ([a-z-]+)\\s+.+\n"
    save: helps

  - name: read aliases
    operation: assert_regex_section
    regex: "^([a-z]+): ([a-z-\\s]+)\n"
    save: aliases
    splits:
      - group: 2

  - name: read commands until eof
    operation: assert_sequence_begins
    count: -1
    rules:

      - name: read command entry
        operation: assert_regex
        regex: "^([a-z-]+):\n"
        save: commands

      - name: read command contents
        operation: assert_regex_section
        regex: "^\t@.+\n"

validators:
  - name: print some variables
    operation: validate_debug
    saved:
      - aliases.capture.capture.unique
